import Footer from "@/components/Footer";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <Header />
      <main className="grow">{children}</main>
      <Footer />
    </html>
  );
}
